WARNING 2025-10-25 15:11:51,993 log Not Found: /favicon.ico
WARNING 2025-10-25 15:11:51,994 basehttp "GET /favicon.ico HTTP/1.1" 404 1240
WARNING 2025-10-25 15:12:02,587 log Not Found: /favicon.ico
WARNING 2025-10-25 15:12:02,588 basehttp "GET /favicon.ico HTTP/1.1" 404 1220
ERROR 2025-10-25 15:12:18,297 log Internal Server Error: /product/4/
Traceback (most recent call last):
  File "C:\Users\seva\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seva\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seva\Desktop\last\banyana_fresh\banyana_fresh\shop\views.py", line 91, in product_detail
    Prefetch('images', queryset=ProductImage.objects.order_by('order'))
                                ^^^^^^^^^^^^
NameError: name 'ProductImage' is not defined
ERROR 2025-10-25 15:12:18,301 basehttp "GET /product/4/ HTTP/1.1" 500 11561
WARNING 2025-10-25 15:13:56,940 log Not Found: /favicon.ico
WARNING 2025-10-25 15:13:56,941 basehttp "GET /favicon.ico HTTP/1.1" 404 1286
WARNING 2025-10-25 15:14:43,488 log Not Found: /favicon.ico
WARNING 2025-10-25 15:14:43,488 basehttp "GET /favicon.ico HTTP/1.1" 404 1265
WARNING 2025-10-25 15:15:43,211 log Not Found: /favicon.ico
WARNING 2025-10-25 15:15:43,212 basehttp "GET /favicon.ico HTTP/1.1" 404 1255
WARNING 2025-10-25 15:15:59,435 log Not Found: /favicon.ico
WARNING 2025-10-25 15:15:59,436 basehttp "GET /favicon.ico HTTP/1.1" 404 1287
WARNING 2025-10-25 15:16:40,379 log Not Found: /favicon.ico
WARNING 2025-10-25 15:16:40,380 basehttp "GET /favicon.ico HTTP/1.1" 404 1295
WARNING 2025-10-25 15:16:52,244 log Not Found: /favicon.ico
WARNING 2025-10-25 15:16:52,245 basehttp "GET /favicon.ico HTTP/1.1" 404 1225
WARNING 2025-10-25 15:16:54,497 log Not Found: /favicon.ico
WARNING 2025-10-25 15:16:54,498 basehttp "GET /favicon.ico HTTP/1.1" 404 1263
WARNING 2025-10-25 15:17:13,137 log Not Found: /favicon.ico
WARNING 2025-10-25 15:17:13,138 basehttp "GET /favicon.ico HTTP/1.1" 404 1249
WARNING 2025-10-25 15:29:50,613 log Not Found: /favicon.ico
WARNING 2025-10-25 15:29:50,613 basehttp "GET /favicon.ico HTTP/1.1" 404 1233
WARNING 2025-10-25 15:30:02,312 log Not Found: /favicon.ico
WARNING 2025-10-25 15:30:02,313 basehttp "GET /favicon.ico HTTP/1.1" 404 1285
WARNING 2025-10-25 15:31:01,133 log Not Found: /favicon.ico
WARNING 2025-10-25 15:31:01,134 basehttp "GET /favicon.ico HTTP/1.1" 404 1298
WARNING 2025-10-25 15:32:09,815 log Not Found: /favicon.ico
WARNING 2025-10-25 15:32:09,816 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-25 15:39:59,077 log Not Found: /favicon.ico
WARNING 2025-10-25 15:39:59,077 basehttp "GET /favicon.ico HTTP/1.1" 404 1296
WARNING 2025-10-25 15:45:44,099 log Not Found: /favicon.ico
WARNING 2025-10-25 15:45:44,100 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-25 15:45:47,730 log Not Found: /favicon.ico
WARNING 2025-10-25 15:45:47,730 basehttp "GET /favicon.ico HTTP/1.1" 404 1268
WARNING 2025-10-25 15:45:54,118 log Not Found: /favicon.ico
WARNING 2025-10-25 15:45:54,118 basehttp "GET /favicon.ico HTTP/1.1" 404 1250
WARNING 2025-10-25 18:50:40,723 log Not Found: /favicon.ico
WARNING 2025-10-25 18:50:40,724 basehttp "GET /favicon.ico HTTP/1.1" 404 1282
WARNING 2025-10-25 18:56:40,717 log Not Found: /static/css/style.css
WARNING 2025-10-25 18:56:40,717 log Not Found: /static/js/main.js
WARNING 2025-10-25 18:56:40,718 basehttp "GET /static/js/main.js HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,718 basehttp "GET /static/css/style.css HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,763 log Not Found: /media/products/photo_6_2025-10-15_18-44-08.jpg
WARNING 2025-10-25 18:56:40,764 log Not Found: /media/products/photo_4_2025-10-15_18-40-21.jpg
WARNING 2025-10-25 18:56:40,765 log Not Found: /media/products/NVIDIA_Overlay_lsAUum10Xu.png
WARNING 2025-10-25 18:56:40,766 basehttp "GET /media/products/photo_6_2025-10-15_18-44-08.jpg HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,767 basehttp "GET /media/products/photo_4_2025-10-15_18-40-21.jpg HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,767 basehttp "GET /media/products/NVIDIA_Overlay_lsAUum10Xu.png HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,795 log Not Found: /favicon.ico
WARNING 2025-10-25 18:56:40,796 basehttp "GET /favicon.ico HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:49,987 log Not Found: /favicon.ico
WARNING 2025-10-25 18:56:49,988 basehttp "GET /favicon.ico HTTP/1.1" 404 1298
WARNING 2025-10-26 14:02:02,515 log Not Found: /favicon.ico
WARNING 2025-10-26 14:02:02,515 basehttp "GET /favicon.ico HTTP/1.1" 404 1289
WARNING 2025-10-26 14:02:04,650 log Not Found: /favicon.ico
WARNING 2025-10-26 14:02:04,650 basehttp "GET /favicon.ico HTTP/1.1" 404 1265
WARNING 2025-10-26 14:28:10,722 log Not Found: /favicon.ico
WARNING 2025-10-26 14:28:10,722 basehttp "GET /favicon.ico HTTP/1.1" 404 1240
WARNING 2025-10-26 14:28:27,789 log Not Found: /favicon.ico
WARNING 2025-10-26 14:28:27,791 basehttp "GET /favicon.ico HTTP/1.1" 404 1301
WARNING 2025-10-26 14:38:52,488 log Not Found: /favicon.ico
WARNING 2025-10-26 14:38:52,488 basehttp "GET /favicon.ico HTTP/1.1" 404 1253
WARNING 2025-10-26 14:42:51,506 log Not Found: /favicon.ico
WARNING 2025-10-26 14:42:51,506 basehttp "GET /favicon.ico HTTP/1.1" 404 1247
WARNING 2025-10-26 14:42:53,673 log Not Found: /favicon.ico
WARNING 2025-10-26 14:42:53,674 basehttp "GET /favicon.ico HTTP/1.1" 404 1284
WARNING 2025-10-26 14:43:01,998 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:01,998 basehttp "GET /favicon.ico HTTP/1.1" 404 1284
WARNING 2025-10-26 14:43:04,253 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:04,254 basehttp "GET /favicon.ico HTTP/1.1" 404 1248
WARNING 2025-10-26 14:43:09,299 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:09,300 basehttp "GET /favicon.ico HTTP/1.1" 404 1247
WARNING 2025-10-26 14:43:15,905 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:15,905 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-26 14:43:20,517 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:20,518 basehttp "GET /favicon.ico HTTP/1.1" 404 1285
WARNING 2025-10-26 14:45:23,976 log Not Found: /favicon.ico
WARNING 2025-10-26 14:45:23,976 basehttp "GET /favicon.ico HTTP/1.1" 404 1284
WARNING 2025-10-26 14:48:04,157 log Not Found: /favicon.ico
WARNING 2025-10-26 14:48:04,157 basehttp "GET /favicon.ico HTTP/1.1" 404 1213
WARNING 2025-10-26 14:48:41,358 log Not Found: /favicon.ico
WARNING 2025-10-26 14:48:41,360 basehttp "GET /favicon.ico HTTP/1.1" 404 1281
WARNING 2025-10-26 14:48:49,248 log Not Found: /favicon.ico
WARNING 2025-10-26 14:48:49,249 basehttp "GET /favicon.ico HTTP/1.1" 404 1227
WARNING 2025-10-26 22:14:44,520 log Not Found: /favicon.ico
WARNING 2025-10-26 22:14:44,520 basehttp "GET /favicon.ico HTTP/1.1" 404 1296
WARNING 2025-10-26 23:45:07,946 log Not Found: /favicon.ico
WARNING 2025-10-26 23:45:07,947 basehttp "GET /favicon.ico HTTP/1.1" 404 1246
WARNING 2025-10-26 23:56:29,241 log Not Found: /favicon.ico
WARNING 2025-10-26 23:56:29,242 basehttp "GET /favicon.ico HTTP/1.1" 404 1262
WARNING 2025-10-26 23:56:33,212 log Not Found: /favicon.ico
WARNING 2025-10-26 23:56:33,213 basehttp "GET /favicon.ico HTTP/1.1" 404 1296
ERROR 2025-10-27 00:17:38,227 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: shop_product.updated_at

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\banya\banya\banya\garantgroupvologda-main\garantgroupvologda-main\shop\views.py", line 37, in index
    featured_products = list(
        Product.objects.select_related()
        .prefetch_related('prices', 'images')
        .all()[:3]
    )
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: shop_product.updated_at
ERROR 2025-10-27 00:17:38,237 basehttp "GET / HTTP/1.1" 500 16752
WARNING 2025-10-27 00:32:25,903 log Not Found: /favicon.ico
WARNING 2025-10-27 00:32:25,903 basehttp "GET /favicon.ico HTTP/1.1" 404 1236
