WARNING 2025-10-25 15:11:51,993 log Not Found: /favicon.ico
WARNING 2025-10-25 15:11:51,994 basehttp "GET /favicon.ico HTTP/1.1" 404 1240
WARNING 2025-10-25 15:12:02,587 log Not Found: /favicon.ico
WARNING 2025-10-25 15:12:02,588 basehttp "GET /favicon.ico HTTP/1.1" 404 1220
ERROR 2025-10-25 15:12:18,297 log Internal Server Error: /product/4/
Traceback (most recent call last):
  File "C:\Users\seva\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seva\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seva\Desktop\last\banyana_fresh\banyana_fresh\shop\views.py", line 91, in product_detail
    Prefetch('images', queryset=ProductImage.objects.order_by('order'))
                                ^^^^^^^^^^^^
NameError: name 'ProductImage' is not defined
ERROR 2025-10-25 15:12:18,301 basehttp "GET /product/4/ HTTP/1.1" 500 11561
WARNING 2025-10-25 15:13:56,940 log Not Found: /favicon.ico
WARNING 2025-10-25 15:13:56,941 basehttp "GET /favicon.ico HTTP/1.1" 404 1286
WARNING 2025-10-25 15:14:43,488 log Not Found: /favicon.ico
WARNING 2025-10-25 15:14:43,488 basehttp "GET /favicon.ico HTTP/1.1" 404 1265
WARNING 2025-10-25 15:15:43,211 log Not Found: /favicon.ico
WARNING 2025-10-25 15:15:43,212 basehttp "GET /favicon.ico HTTP/1.1" 404 1255
WARNING 2025-10-25 15:15:59,435 log Not Found: /favicon.ico
WARNING 2025-10-25 15:15:59,436 basehttp "GET /favicon.ico HTTP/1.1" 404 1287
WARNING 2025-10-25 15:16:40,379 log Not Found: /favicon.ico
WARNING 2025-10-25 15:16:40,380 basehttp "GET /favicon.ico HTTP/1.1" 404 1295
WARNING 2025-10-25 15:16:52,244 log Not Found: /favicon.ico
WARNING 2025-10-25 15:16:52,245 basehttp "GET /favicon.ico HTTP/1.1" 404 1225
WARNING 2025-10-25 15:16:54,497 log Not Found: /favicon.ico
WARNING 2025-10-25 15:16:54,498 basehttp "GET /favicon.ico HTTP/1.1" 404 1263
WARNING 2025-10-25 15:17:13,137 log Not Found: /favicon.ico
WARNING 2025-10-25 15:17:13,138 basehttp "GET /favicon.ico HTTP/1.1" 404 1249
WARNING 2025-10-25 15:29:50,613 log Not Found: /favicon.ico
WARNING 2025-10-25 15:29:50,613 basehttp "GET /favicon.ico HTTP/1.1" 404 1233
WARNING 2025-10-25 15:30:02,312 log Not Found: /favicon.ico
WARNING 2025-10-25 15:30:02,313 basehttp "GET /favicon.ico HTTP/1.1" 404 1285
WARNING 2025-10-25 15:31:01,133 log Not Found: /favicon.ico
WARNING 2025-10-25 15:31:01,134 basehttp "GET /favicon.ico HTTP/1.1" 404 1298
WARNING 2025-10-25 15:32:09,815 log Not Found: /favicon.ico
WARNING 2025-10-25 15:32:09,816 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-25 15:39:59,077 log Not Found: /favicon.ico
WARNING 2025-10-25 15:39:59,077 basehttp "GET /favicon.ico HTTP/1.1" 404 1296
WARNING 2025-10-25 15:45:44,099 log Not Found: /favicon.ico
WARNING 2025-10-25 15:45:44,100 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-25 15:45:47,730 log Not Found: /favicon.ico
WARNING 2025-10-25 15:45:47,730 basehttp "GET /favicon.ico HTTP/1.1" 404 1268
WARNING 2025-10-25 15:45:54,118 log Not Found: /favicon.ico
WARNING 2025-10-25 15:45:54,118 basehttp "GET /favicon.ico HTTP/1.1" 404 1250
WARNING 2025-10-25 18:50:40,723 log Not Found: /favicon.ico
WARNING 2025-10-25 18:50:40,724 basehttp "GET /favicon.ico HTTP/1.1" 404 1282
WARNING 2025-10-25 18:56:40,717 log Not Found: /static/css/style.css
WARNING 2025-10-25 18:56:40,717 log Not Found: /static/js/main.js
WARNING 2025-10-25 18:56:40,718 basehttp "GET /static/js/main.js HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,718 basehttp "GET /static/css/style.css HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,763 log Not Found: /media/products/photo_6_2025-10-15_18-44-08.jpg
WARNING 2025-10-25 18:56:40,764 log Not Found: /media/products/photo_4_2025-10-15_18-40-21.jpg
WARNING 2025-10-25 18:56:40,765 log Not Found: /media/products/NVIDIA_Overlay_lsAUum10Xu.png
WARNING 2025-10-25 18:56:40,766 basehttp "GET /media/products/photo_6_2025-10-15_18-44-08.jpg HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,767 basehttp "GET /media/products/photo_4_2025-10-15_18-40-21.jpg HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,767 basehttp "GET /media/products/NVIDIA_Overlay_lsAUum10Xu.png HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:40,795 log Not Found: /favicon.ico
WARNING 2025-10-25 18:56:40,796 basehttp "GET /favicon.ico HTTP/1.1" 404 179
WARNING 2025-10-25 18:56:49,987 log Not Found: /favicon.ico
WARNING 2025-10-25 18:56:49,988 basehttp "GET /favicon.ico HTTP/1.1" 404 1298
WARNING 2025-10-26 14:02:02,515 log Not Found: /favicon.ico
WARNING 2025-10-26 14:02:02,515 basehttp "GET /favicon.ico HTTP/1.1" 404 1289
WARNING 2025-10-26 14:02:04,650 log Not Found: /favicon.ico
WARNING 2025-10-26 14:02:04,650 basehttp "GET /favicon.ico HTTP/1.1" 404 1265
WARNING 2025-10-26 14:28:10,722 log Not Found: /favicon.ico
WARNING 2025-10-26 14:28:10,722 basehttp "GET /favicon.ico HTTP/1.1" 404 1240
WARNING 2025-10-26 14:28:27,789 log Not Found: /favicon.ico
WARNING 2025-10-26 14:28:27,791 basehttp "GET /favicon.ico HTTP/1.1" 404 1301
WARNING 2025-10-26 14:38:52,488 log Not Found: /favicon.ico
WARNING 2025-10-26 14:38:52,488 basehttp "GET /favicon.ico HTTP/1.1" 404 1253
WARNING 2025-10-26 14:42:51,506 log Not Found: /favicon.ico
WARNING 2025-10-26 14:42:51,506 basehttp "GET /favicon.ico HTTP/1.1" 404 1247
WARNING 2025-10-26 14:42:53,673 log Not Found: /favicon.ico
WARNING 2025-10-26 14:42:53,674 basehttp "GET /favicon.ico HTTP/1.1" 404 1284
WARNING 2025-10-26 14:43:01,998 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:01,998 basehttp "GET /favicon.ico HTTP/1.1" 404 1284
WARNING 2025-10-26 14:43:04,253 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:04,254 basehttp "GET /favicon.ico HTTP/1.1" 404 1248
WARNING 2025-10-26 14:43:09,299 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:09,300 basehttp "GET /favicon.ico HTTP/1.1" 404 1247
WARNING 2025-10-26 14:43:15,905 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:15,905 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-26 14:43:20,517 log Not Found: /favicon.ico
WARNING 2025-10-26 14:43:20,518 basehttp "GET /favicon.ico HTTP/1.1" 404 1285
WARNING 2025-10-26 14:45:23,976 log Not Found: /favicon.ico
WARNING 2025-10-26 14:45:23,976 basehttp "GET /favicon.ico HTTP/1.1" 404 1284
WARNING 2025-10-26 14:48:04,157 log Not Found: /favicon.ico
WARNING 2025-10-26 14:48:04,157 basehttp "GET /favicon.ico HTTP/1.1" 404 1213
WARNING 2025-10-26 14:48:41,358 log Not Found: /favicon.ico
WARNING 2025-10-26 14:48:41,360 basehttp "GET /favicon.ico HTTP/1.1" 404 1281
WARNING 2025-10-26 14:48:49,248 log Not Found: /favicon.ico
WARNING 2025-10-26 14:48:49,249 basehttp "GET /favicon.ico HTTP/1.1" 404 1227
WARNING 2025-10-26 22:14:44,520 log Not Found: /favicon.ico
WARNING 2025-10-26 22:14:44,520 basehttp "GET /favicon.ico HTTP/1.1" 404 1296
WARNING 2025-10-26 23:45:07,946 log Not Found: /favicon.ico
WARNING 2025-10-26 23:45:07,947 basehttp "GET /favicon.ico HTTP/1.1" 404 1246
WARNING 2025-10-26 23:56:29,241 log Not Found: /favicon.ico
WARNING 2025-10-26 23:56:29,242 basehttp "GET /favicon.ico HTTP/1.1" 404 1262
WARNING 2025-10-26 23:56:33,212 log Not Found: /favicon.ico
WARNING 2025-10-26 23:56:33,213 basehttp "GET /favicon.ico HTTP/1.1" 404 1296
ERROR 2025-10-27 00:17:38,227 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: shop_product.updated_at

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\banya\banya\banya\garantgroupvologda-main\garantgroupvologda-main\shop\views.py", line 37, in index
    featured_products = list(
        Product.objects.select_related()
        .prefetch_related('prices', 'images')
        .all()[:3]
    )
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: shop_product.updated_at
ERROR 2025-10-27 00:17:38,237 basehttp "GET / HTTP/1.1" 500 16752
WARNING 2025-10-27 00:32:25,903 log Not Found: /favicon.ico
WARNING 2025-10-27 00:32:25,903 basehttp "GET /favicon.ico HTTP/1.1" 404 1236
WARNING 2025-10-27 15:26:19,707 log Not Found: /favicon.ico
WARNING 2025-10-27 15:26:19,708 basehttp "GET /favicon.ico HTTP/1.1" 404 1211
WARNING 2025-10-27 15:40:57,695 log Not Found: /favicon.ico
WARNING 2025-10-27 15:40:57,696 basehttp "GET /favicon.ico HTTP/1.1" 404 1258
WARNING 2025-10-27 15:41:10,348 log Not Found: /favicon.ico
WARNING 2025-10-27 15:41:10,348 basehttp "GET /favicon.ico HTTP/1.1" 404 1301
WARNING 2025-10-27 15:55:30,509 log Not Found: /favicon.ico
WARNING 2025-10-27 15:55:30,509 basehttp "GET /favicon.ico HTTP/1.1" 404 1237
ERROR 2025-10-27 15:55:34,114 log Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\banya\banya\banya\garantgroupvologda-main\garantgroupvologda-main\shop\views.py", line 50, in about
    return render(request, 'shop/about.html', {'info': info})
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contacts' not found. 'contacts' is not a valid view function or pattern name.
ERROR 2025-10-27 15:55:34,124 basehttp "GET /about/ HTTP/1.1" 500 18603
WARNING 2025-10-27 15:55:42,970 log Not Found: /favicon.ico
WARNING 2025-10-27 15:55:42,970 basehttp "GET /favicon.ico HTTP/1.1" 404 1223
ERROR 2025-10-27 15:55:43,896 log Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\banya\banya\banya\garantgroupvologda-main\garantgroupvologda-main\shop\views.py", line 50, in about
    return render(request, 'shop/about.html', {'info': info})
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contacts' not found. 'contacts' is not a valid view function or pattern name.
ERROR 2025-10-27 15:55:43,902 basehttp "GET /about/ HTTP/1.1" 500 18510
WARNING 2025-10-27 15:55:52,831 log Not Found: /favicon.ico
WARNING 2025-10-27 15:55:52,832 basehttp "GET /favicon.ico HTTP/1.1" 404 1283
WARNING 2025-10-27 15:56:10,949 log Not Found: /favicon.ico
WARNING 2025-10-27 15:56:10,950 basehttp "GET /favicon.ico HTTP/1.1" 404 1215
WARNING 2025-10-27 15:56:32,656 log Not Found: /favicon.ico
WARNING 2025-10-27 15:56:32,656 basehttp "GET /favicon.ico HTTP/1.1" 404 1251
WARNING 2025-10-27 15:56:49,417 log Not Found: /favicon.ico
WARNING 2025-10-27 15:56:49,417 basehttp "GET /favicon.ico HTTP/1.1" 404 1300
WARNING 2025-10-27 15:56:53,113 log Not Found: /favicon.ico
WARNING 2025-10-27 15:56:53,113 basehttp "GET /favicon.ico HTTP/1.1" 404 1244
WARNING 2025-10-27 15:58:04,744 log Not Found: /favicon.ico
WARNING 2025-10-27 15:58:04,745 basehttp "GET /favicon.ico HTTP/1.1" 404 1219
WARNING 2025-10-27 15:58:22,125 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 15:58:22,126 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1241
WARNING 2025-10-27 15:58:38,237 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 15:58:38,238 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1267
WARNING 2025-10-27 15:59:43,698 log Not Found: /favicon.ico
WARNING 2025-10-27 15:59:43,699 basehttp "GET /favicon.ico HTTP/1.1" 404 1227
WARNING 2025-10-27 16:00:20,563 log Not Found: /favicon.ico
WARNING 2025-10-27 16:00:20,564 basehttp "GET /favicon.ico HTTP/1.1" 404 1305
WARNING 2025-10-27 16:01:11,915 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:01:11,916 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1336
WARNING 2025-10-27 16:01:54,675 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:01:54,675 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1269
WARNING 2025-10-27 16:01:56,779 log Not Found: /favicon.ico
WARNING 2025-10-27 16:01:56,780 basehttp "GET /favicon.ico HTTP/1.1" 404 1301
WARNING 2025-10-27 16:02:04,694 log Not Found: /favicon.ico
WARNING 2025-10-27 16:02:04,695 basehttp "GET /favicon.ico HTTP/1.1" 404 1269
WARNING 2025-10-27 16:02:36,120 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:02:36,121 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1252
WARNING 2025-10-27 16:03:18,857 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:03:18,857 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1328
WARNING 2025-10-27 16:03:18,984 log Not Found: /favicon.ico
WARNING 2025-10-27 16:03:18,985 basehttp "GET /favicon.ico HTTP/1.1" 404 1266
WARNING 2025-10-27 16:03:36,214 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:03:36,215 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1323
WARNING 2025-10-27 16:03:36,321 log Not Found: /favicon.ico
WARNING 2025-10-27 16:03:36,322 basehttp "GET /favicon.ico HTTP/1.1" 404 1237
WARNING 2025-10-27 16:06:03,469 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:06:03,470 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1323
WARNING 2025-10-27 16:10:14,786 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:10:14,787 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1300
WARNING 2025-10-27 16:11:46,917 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:11:46,919 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1303
WARNING 2025-10-27 16:11:47,260 log Not Found: /favicon.ico
WARNING 2025-10-27 16:11:47,260 basehttp "GET /favicon.ico HTTP/1.1" 404 1225
WARNING 2025-10-27 16:11:52,430 log Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-27 16:11:52,431 basehttp "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1278
WARNING 2025-10-27 16:11:52,558 log Not Found: /favicon.ico
WARNING 2025-10-27 16:11:52,558 basehttp "GET /favicon.ico HTTP/1.1" 404 1301
WARNING 2025-10-27 16:16:41,023 log Not Found: /favicon.ico
WARNING 2025-10-27 16:16:41,024 basehttp "GET /favicon.ico HTTP/1.1" 404 1250
WARNING 2025-10-27 16:16:42,763 log Not Found: /favicon.ico
WARNING 2025-10-27 16:16:42,764 basehttp "GET /favicon.ico HTTP/1.1" 404 1249
WARNING 2025-10-27 16:29:33,928 log Not Found: /favicon.ico
WARNING 2025-10-27 16:29:33,929 basehttp "GET /favicon.ico HTTP/1.1" 404 1300
WARNING 2025-10-27 16:33:32,450 log Not Found: /favicon.ico
WARNING 2025-10-27 16:33:32,451 basehttp "GET /favicon.ico HTTP/1.1" 404 1257
WARNING 2025-10-27 16:51:56,028 log Not Found: /favicon.ico
WARNING 2025-10-27 16:51:56,028 basehttp "GET /favicon.ico HTTP/1.1" 404 1215
WARNING 2025-10-27 16:52:54,799 log Not Found: /favicon.ico
WARNING 2025-10-27 16:52:54,799 basehttp "GET /favicon.ico HTTP/1.1" 404 1288
WARNING 2025-10-27 16:59:47,624 log Not Found: /favicon.ico
WARNING 2025-10-27 16:59:47,625 basehttp "GET /favicon.ico HTTP/1.1" 404 1237
WARNING 2025-10-27 17:04:09,909 log Not Found: /favicon.ico
WARNING 2025-10-27 17:04:09,909 basehttp "GET /favicon.ico HTTP/1.1" 404 1263
WARNING 2025-10-27 17:07:56,017 log Not Found: /favicon.ico
WARNING 2025-10-27 17:07:56,018 basehttp "GET /favicon.ico HTTP/1.1" 404 1226
WARNING 2025-10-27 18:35:28,478 basehttp "GET /static/images/logo-placeholder.png HTTP/1.1" 404 2008
WARNING 2025-10-27 18:35:28,896 log Not Found: /favicon.ico
WARNING 2025-10-27 18:35:28,897 basehttp "GET /favicon.ico HTTP/1.1" 404 1290
WARNING 2025-10-27 18:35:31,251 basehttp "GET /static/images/logo-placeholder.png HTTP/1.1" 404 2008
WARNING 2025-10-27 18:35:31,627 log Not Found: /favicon.ico
WARNING 2025-10-27 18:35:31,628 basehttp "GET /favicon.ico HTTP/1.1" 404 1272
WARNING 2025-10-27 18:35:51,576 log Bad Request: /credit-request/
WARNING 2025-10-27 18:35:51,576 basehttp "POST /credit-request/ HTTP/1.1" 400 253
WARNING 2025-10-27 18:42:05,482 log Not Found: /favicon.ico
WARNING 2025-10-27 18:42:05,483 basehttp "GET /favicon.ico HTTP/1.1" 404 1321
WARNING 2025-10-27 18:42:18,689 log Bad Request: /credit-request/
WARNING 2025-10-27 18:42:18,689 basehttp "POST /credit-request/ HTTP/1.1" 400 176
WARNING 2025-10-27 18:42:18,698 log Gone: /captcha/image/144087855e2b075f4f48305059a1e8760b3a1fb4/
WARNING 2025-10-27 18:42:18,699 basehttp "GET /captcha/image/144087855e2b075f4f48305059a1e8760b3a1fb4/?1761579738695 HTTP/1.1" 410 0
WARNING 2025-10-27 18:42:22,684 log Not Found: /favicon.ico
WARNING 2025-10-27 18:42:22,685 basehttp "GET /favicon.ico HTTP/1.1" 404 1317
WARNING 2025-10-27 18:42:30,439 log Bad Request: /credit-request/
WARNING 2025-10-27 18:42:30,439 basehttp "POST /credit-request/ HTTP/1.1" 400 244
WARNING 2025-10-27 18:42:30,443 log Gone: /captcha/image/2b53c818bef35489a2de1f34e66b92933119e113/
WARNING 2025-10-27 18:42:30,443 basehttp "GET /captcha/image/2b53c818bef35489a2de1f34e66b92933119e113/?1761579750441 HTTP/1.1" 410 0
WARNING 2025-10-27 18:42:35,232 log Not Found: /favicon.ico
WARNING 2025-10-27 18:42:35,233 basehttp "GET /favicon.ico HTTP/1.1" 404 1239
WARNING 2025-10-27 18:42:46,144 log Bad Request: /credit-request/
WARNING 2025-10-27 18:42:46,145 basehttp "POST /credit-request/ HTTP/1.1" 400 176
WARNING 2025-10-27 18:42:46,149 log Gone: /captcha/image/826ec83384c734b7acc2bb859613d415c45fbf90/
WARNING 2025-10-27 18:42:46,149 basehttp "GET /captcha/image/826ec83384c734b7acc2bb859613d415c45fbf90/?1761579766146 HTTP/1.1" 410 0
WARNING 2025-10-27 18:54:52,098 log Not Found: /favicon.ico
WARNING 2025-10-27 18:54:52,099 basehttp "GET /favicon.ico HTTP/1.1" 404 1248
WARNING 2025-10-27 18:55:13,668 log Bad Request: /credit-request/
WARNING 2025-10-27 18:55:13,669 basehttp "POST /credit-request/ HTTP/1.1" 400 176
WARNING 2025-10-27 18:55:13,675 log Gone: /captcha/image/3d70451d4b405b4ec8017ccab0ff54e78da3ab2d/
WARNING 2025-10-27 18:55:13,676 basehttp "GET /captcha/image/3d70451d4b405b4ec8017ccab0ff54e78da3ab2d/?1761580513672 HTTP/1.1" 410 0
WARNING 2025-10-27 18:55:17,514 log Not Found: /favicon.ico
WARNING 2025-10-27 18:55:17,515 basehttp "GET /favicon.ico HTTP/1.1" 404 1229
WARNING 2025-10-27 18:58:30,807 log Not Found: /favicon.ico
WARNING 2025-10-27 18:58:30,807 basehttp "GET /favicon.ico HTTP/1.1" 404 1289
WARNING 2025-10-27 18:58:54,298 log Not Found: /favicon.ico
WARNING 2025-10-27 18:58:54,298 basehttp "GET /favicon.ico HTTP/1.1" 404 1238
WARNING 2025-10-27 19:10:45,652 log Not Found: /favicon.ico
WARNING 2025-10-27 19:10:45,653 basehttp "GET /favicon.ico HTTP/1.1" 404 1240
